name: gssoc21

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, 'YES') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: gssoc21
